apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-app
spec:
  project: default
  source:
    repoURL: https://github.com/pseudonative/profile_page_k8s.git
    path: kubernetes
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false