# name: CI to Docker Hub & Deploy to Kubernetes

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2

#     - name: Build and Push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: user/myapp:latest

#   deploy-to-k8s:
#     needs: build-and-push
#     runs-on: ubuntu-latest
#     steps:
#     - name: Check Out Repo
#       uses: actions/checkout@v2

#     - name: Set up Kubectl
#       uses: azure/setup-kubectl@v1

#     - name: Deploy to Kubernetes
#       run: |
#         kubectl set image deployment/myapp-deployment myapp=user/myapp:latest
#         # Other Kubernetes commands to update the deployment can also be added here